BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "speedrun" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"GameId"	TEXT NOT NULL,
	"RunId"	TEXT NOT NULL,
	"SpeedrunLink"	TEXT NOT NULL,
	"Game"	TEXT,
	"Category"	TEXT,
	"Date"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
